version: 2
updates:
  # Actualizări pentru backend (inventory‑api)
  - package-ecosystem: "npm"
    directory: "/inventory-api"
    schedule:
      interval: "daily"
    # opțional poți activa și pentru devDependencies:
    # open-pull-requests-limit: 10
    # allow:
    #   - dependency-type: "all"

  # Actualizări pentru frontend (web)
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    # open-pull-requests-limit: 10
    # allow:
    #   - dependency-type: "all"
