name: Build & Push UI Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GHCR_PAT }}" \
            | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build UI image
        run: |
          docker build \
            --file web/Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/inventory-ui:latest \
            web

      - name: Push UI image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/inventory-ui:latest
