name: Build & Push API Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch, optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_PAT }}" \
            | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build API image
        run: |
          docker build \
            --file inventory-api/Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/inventory-api:latest \
            inventory-api

      - name: Run integration tests
        working-directory: inventory-api
        run: |
          npm install
          npm run test:int

      - name: Push API image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/inventory-api:latest